### ISSUE TITLE
Refer to proper installation of Flutter

### ISSUE THREAD

**Issue by blelump** [THCLab/dkms-demo-android#3]
See section 
https://github.com/THCLab/dkms-demo/tree/main/controller2_mobile_app#how-to-find-install-and-configure-the-right-version-of-flutter

**Comment by henkvancann** [comment]
Background: I need to know which Flutter app. There are many available. Provide a link?

**Comment by blelump** [comment]
@henkvancann , does https://github.com/THCLab/dkms-demo/commit/7480e9ba2e358d7f68ef170fbf6743caa9501222 makes sense (already merged)?

**Comment by henkvancann** [comment]
Working through this file: 
https://github.com/THCLab/dkms-demo/tree/main/controller2_mobile_app#finding-the-right-android-studio-version.
The link is broken "the official IDE website" https://developer.android.com/android-studio/download . Was it tested? I think you mean this one? https://developer.android.com/studio#downloads ?

NB. Just to inform you about the confusion the former description generated: I installed Android Studio app on my phone (!) from the Google Play site. I removed that one, because I think I need Android Studio on my desktop computer, but this wasn't clear at all.

Android Studio for desktop computer
===========
Again, I think it hasn't been tested, what users encounter when following the guideline. You skip steps.

"follow the on screen instructions for installation." Unfortunately there are choices not accounted for:

<img width="421" alt="Screenshot 2022-07-09 at 16 16 59" src="https://user-images.githubusercontent.com/479356/178111896-1e6a306f-62f2-4ffd-b6f1-76db39d389a3.png">
What should I select?

<img width="728" alt="Screenshot 2022-07-09 at 16 21 04" src="https://user-images.githubusercontent.com/479356/178111989-1e5db849-8a38-4ef8-91ae-d509761b21e8.png">
What should I select?

<img width="748" alt="Screenshot 2022-07-09 at 16 22 32" src="https://user-images.githubusercontent.com/479356/178112010-6690ccd7-3bed-4682-8999-d72acb86ace6.png">
New Project? Or open project in the repo?

Flutter
=====
Good description by the site you link to, but it isn't clear whether I need to install Xcode too. You don't mention it, so a user might stop after having done what you asked for: installing Flutter not Xcode. I think you want Xcode too?

Running the .dart file in Android Studio
=====
Which .dart file?? Where can I find it? Why not a link provided?

2. "run in terminal ...." Can you believe that I've been searching for 15 minutes to find the window of the standard terminal in Android Studio??  Why not inform users where to find the terminal window? In my standard setup there is no toolbar, the help site has no hit on 'terminal' and I've gone through all the items in the menus.

<img width="1173" alt="Screenshot 2022-07-09 at 17 24 01" src="https://user-images.githubusercontent.com/479356/178114491-fc2304a2-56c2-4728-8cdf-fd364dea2127.png">

3. Opening main.dart file in Android Studio - didn't get here because I could find a way to  open a terminal window in Android Studio IDE (step 2.) and run the command. In Visual Studio Code finding a terminal window is easy and logical.

### review

 It's lots of work to document this in issues and find my way through instructions that have unforeseen choices and missing steps. I call it a day, sorry, I don't seem to get the message across that instructions need to be verbose and complete: foresee every choice and anticipate.
Good luck with it.

**Comment by mitfik** [comment]
Project is archived and we are moving from demo to [ambient-infrastructure](https://github.com/THCLab/ambient-infrastructure) project
